name: lint

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: npm install && npm run lint
